INSERT INTO beers (id, name, rating) VALUES (1, 'Heineken', 'GOOD');
INSERT INTO beers (id, name, rating) VALUES (2, 'Guinness', 'EXCELLENT');
INSERT INTO beers (id, name, rating) VALUES (3, 'Budweiser', 'AVERAGE');
INSERT INTO beers (id, name, rating) VALUES (4, 'Corona', 'GOOD');
INSERT INTO beers (id, name, rating) VALUES (5, 'Sierra Nevada', 'EXCELLENT');
INSERT INTO beers (id, name, rating) VALUES (6, 'Coors Light', 'POOR');
INSERT INTO beers (id, name, rating) VALUES (7, 'Blue Moon', 'AVERAGE');
INSERT INTO beers (id, name, rating) VALUES (8, 'Pilsner Urquell', 'GOOD');
INSERT INTO beers (id, name, rating) VALUES (9, 'Miller Lite', 'POOR');
INSERT INTO beers (id, name, rating) VALUES (10, 'Lagunitas IPA', 'EXCELLENT');
